-- Lorefriendly-Cars
['akumac'] = {
    ['name'] = 'Akuma Classic',
    ['brand'] = 'Dinka',
    ['model'] = 'akumac',
    ['price'] = 56000,
    ['category'] = 'motorcycles',
    ['hash'] = `akumac`,
    ['shop'] = 'pdm',
},
['atlas'] = {
    ['name'] = 'Atlas',
    ['brand'] = 'Karin',
    ['model'] = 'atlas',
    ['price'] = 29000,
    ['category'] = 'suvs',
    ['hash'] = `atlas`,
    ['shop'] = 'pdm',
},
['arias'] = {
    ['name'] = 'Arias',
    ['brand'] = 'Bordeaux',
    ['model'] = 'arias',
    ['price'] = 11000,
    ['category'] = 'compacts',
    ['hash'] = `arias`,
    ['shop'] = 'pdm',
},
['baller7r'] = {
    ['name'] = 'Baller Raid',
    ['brand'] = 'Gallivanter',
    ['model'] = 'baller7r',
    ['price'] = 35000,
    ['category'] = 'offroad',
    ['hash'] = `baller7r`,
    ['shop'] = 'pdm',
},
['benson2'] = {
    ['name'] = 'Benson',
    ['brand'] = 'Vapid',
    ['model'] = 'benson2',
    ['price'] = 59000,
    ['category'] = 'utility',
    ['hash'] = `benson2`,
    ['shop'] = 'pdm',
},
['blazer6'] = {
    ['name'] = 'Blazer Recon ATV',
    ['brand'] = 'Nagasaki',
    ['model'] = 'blazer6',
    ['price'] = 11000,
    ['category'] = 'offroad',
    ['hash'] = `blazer6`,
    ['shop'] = 'pdm',
},
['buffalo4h'] = {
    ['name'] = 'Buffalo Hellfire',
    ['brand'] = 'Bravado',
    ['model'] = 'buffalo4h',
    ['price'] = 35000,
    ['category'] = 'sports',
    ['hash'] = `buffalo4h`,
    ['shop'] = 'luxury',
},
['burritor'] = {
    ['name'] = 'Burrito Racing',
    ['brand'] = 'Declasse',
    ['model'] = 'burritor',
    ['price'] = 13500,
    ['category'] = 'vans',
    ['hash'] = `burritor`,
    ['shop'] = 'pdm',
},
['cheetahfel'] = {
    ['name'] = 'Cheetah Veloce',
    ['brand'] = 'Grotti',
    ['model'] = 'cheetahfel',
    ['price'] = 311000,
    ['category'] = 'sportsclassics',
    ['hash'] = `cheetahfel`,
    ['shop'] = 'luxury',
},
['clique2'] = {
    ['name'] = 'Clique Deluxe',
    ['brand'] = 'Vapid',
    ['model'] = 'clique2',
    ['price'] = 21500,
    ['category'] = 'coupes',
    ['hash'] = `clique2`,
    ['shop'] = 'pdm',
},
['coquette4c'] = {
    ['name'] = 'Coquette D10 Widebody',
    ['brand'] = 'Invetero',
    ['model'] = 'coquette4c',
    ['price'] = 241000,
    ['category'] = 'sports',
    ['hash'] = `coquette4c`,
    ['shop'] = 'luxury',
},
['domc'] = {
    ['name'] = 'Dominator Classic',
    ['brand'] = 'Vapid',
    ['model'] = 'domc',
    ['price'] = 65000,
    ['category'] = 'muscle',
    ['hash'] = `domc`,
    ['shop'] = 'pdm',
},
['dominatorgtc'] = {
    ['name'] = 'Dominator GTC',
    ['brand'] = 'Vapid',
    ['model'] = 'dominatorgtc',
    ['price'] = 85100,
    ['category'] = 'muscle',
    ['hash'] = `dominatorgtc`,
    ['shop'] = 'pdm',
},
['dukes4'] = {
    ['name'] = 'Dukes Cobra',
    ['brand'] = 'Imponte',
    ['model'] = 'dukes4',
    ['price'] = 81000,
    ['category'] = 'muscle',
    ['hash'] = `dukes4`,
    ['shop'] = 'pdm',
},
['elegant'] = {
    ['name'] = 'Elegant',
    ['brand'] = 'Willard',
    ['model'] = 'elegant',
    ['price'] = 21000,
    ['category'] = 'sedans',
    ['hash'] = `elegant`,
    ['shop'] = 'pdm',
},
['euros'] = {
    ['name'] = 'Euros',
    ['brand'] = 'Annis',
    ['model'] = 'euros',
    ['price'] = 97110,
    ['category'] = 'sports',
    ['hash'] = `euros`,
    ['shop'] = 'luxury',
},
['eva'] = {
    ['name'] = 'EVA',
    ['brand'] = 'Hijak',
    ['model'] = 'eva',
    ['price'] = 55100,
    ['category'] = 'compacts',
    ['hash'] = `eva`,
    ['shop'] = 'pdm',
},
['executioner'] = {
    ['name'] = 'Executioner',
    ['brand'] = 'Vapid',
    ['model'] = 'executioner',
    ['price'] = 32000,
    ['category'] = 'suvs',
    ['hash'] = `executioner`,
    ['shop'] = 'pdm',
},

['f620s2'] = {
    ['name'] = 'F620 Sleeper',
    ['brand'] = 'Ocelot',
    ['model'] = 'f620s2',
    ['price'] = 52500,
    ['category'] = 'sports',
    ['hash'] = `f620s2`,
    ['shop'] = 'luxury',
},
['gauntletc'] = {
    ['name'] = 'Gauntlet Classic',
    ['brand'] = 'Bravado',
    ['model'] = 'gauntletstx',
    ['price'] = 60000,
    ['category'] = 'muscle',
    ['hash'] = `gauntletstx`,
    ['shop'] = 'pdm',
},
['gauntletstx'] = {
    ['name'] = 'Gauntlet STX',
    ['brand'] = 'Bravado',
    ['model'] = 'gauntletstx',
    ['price'] = 76000,
    ['category'] = 'muscle',
    ['hash'] = `gauntletstx`,
    ['shop'] = 'pdm',
},
['glendalelimo'] = {
    ['name'] = 'Glendale Stretch',
    ['brand'] = 'Karin',
    ['model'] = 'glendalelimo',
    ['price'] = 98190,
    ['category'] = 'sedans',
    ['hash'] = `glendalelimo`,
    ['shop'] = 'luxury',
},
['gstyosemite1'] = {
    ['name'] = 'Yosemite DRT',
    ['brand'] = 'Declasse',
    ['model'] = 'gstyosemite1',
    ['price'] = 41000,
    ['category'] = 'offroad',
    ['hash'] = `gstyosemite1`,
    ['shop'] = 'pdm',
},
['hotwee'] = {
    ['name'] = 'Hotring Weevil',
    ['brand'] = 'BF',
    ['model'] = 'hotwee',
    ['price'] = 21000,
    ['category'] = 'compacts',
    ['hash'] = `hotwee`,
    ['shop'] = 'pdm',
},
['italigts'] = {
    ['name'] = 'Itali GTS',
    ['brand'] = 'Grotti',
    ['model'] = 'italigts',
    ['price'] = 271000,
    ['category'] = 'sports',
    ['hash'] = `italigts`,
    ['shop'] = 'luxury',
},
['kampfer'] = {
    ['name'] = 'Kampfer',
    ['brand'] = 'Übermacht',
    ['model'] = 'kampfer',
    ['price'] = 29100,
    ['category'] = 'motorcycles',
    ['hash'] = `kampfer`,
    ['shop'] = 'pdm',
},     
['meteor'] = {
    ['name'] = 'Meteor',
    ['brand'] = 'Pfister',
    ['model'] = 'meteor',
    ['price'] = 210000,
    ['category'] = 'sports',
    ['hash'] = `meteor`,
    ['shop'] = 'luxury',
},
['nspeedo'] = {
    ['name'] = 'Speedo Express',
    ['brand'] = 'Vapid',
    ['model'] = 'nspeedo',
    ['price'] = 21000,
    ['category'] = 'vans',
    ['hash'] = `nspeedo`,
    ['shop'] = 'pdm',
},
['kawaii'] = {
    ['name'] = 'Kawaii',
    ['brand'] = 'Annis',
    ['model'] = 'kawaii',
    ['price'] = 151000,
    ['category'] = 'sports',
    ['hash'] = `kawaii`,
    ['shop'] = 'luxury',
},
['panorama'] = {
    ['name'] = 'Panorama',
    ['brand'] = 'Classique',
    ['model'] = 'panorama',
    ['price'] = 61000,
    ['category'] = 'sedans',
    ['hash'] = `panorama`,
    ['shop'] = 'pdm',
},
['paradox'] = {
    ['name'] = 'Paradox',
    ['brand'] = 'Willard',
    ['model'] = 'paradox',
    ['price'] = 78000,
    ['category'] = 'muscle',
    ['hash'] = `paradox`,
    ['shop'] = 'pdm',
},
['paradox2'] = {
    ['name'] = 'Paradox',
    ['brand'] = 'Willard',
    ['model'] = 'paradox2',
    ['price'] = 79000,
    ['category'] = 'muscle',
    ['hash'] = `paradox2`,
    ['shop'] = 'pdm',
},
['paragonxr'] = {
    ['name'] = 'Paragon XR',
    ['brand'] = 'Enus',
    ['model'] = 'paragonxr',
    ['price'] = 88000,
    ['category'] = 'coupes',
    ['hash'] = `paragonxr`,
    ['shop'] = 'luxury',
},    
['peanut'] = {
    ['name'] = 'Peanut',
    ['brand'] = 'Weeny',
    ['model'] = 'peanut',
    ['price'] = 13000,
    ['category'] = 'compacts',
    ['hash'] = `peanut`,
    ['shop'] = 'pdm',
},
['picadorexr'] = {
    ['name'] = 'Picador EXR',
    ['brand'] = 'Cheval',
    ['model'] = 'picadorexr',
    ['price'] = 51000,
    ['category'] = 'tuner',
    ['hash'] = `picadorexr`,
    ['shop'] = 'luxury',
},
['roxanne'] = {
    ['name'] = 'Roxanne',
    ['brand'] = 'Annis',
    ['model'] = 'roxanne',
    ['price'] = 67000,
    ['category'] = 'tuner',
    ['hash'] = `roxanne`,
    ['shop'] = 'luxury',
},
['sentinelsg4'] = {
    ['name'] = 'Sentinel SG4',
    ['brand'] = 'Übermacht',
    ['model'] = 'sentinelsg4',
    ['price'] = 160000,
    ['category'] = 'coupes',
    ['hash'] = `sentinelsg4`,
    ['shop'] = 'pdm',
},
['sheavas'] = {
    ['name'] = 'Sheava',
    ['brand'] = 'Emperor',
    ['model'] = 'sheavas',
    ['price'] = 210000,
    ['category'] = 'sports',
    ['hash'] = `sheavas`,
    ['shop'] = 'luxury',
},
['stardust'] = {
    ['name'] = 'Stardust',
    ['brand'] = 'Pfister',
    ['model'] = 'stardust',
    ['price'] = 90100,
    ['category'] = 'sportsclassics',
    ['hash'] = `stardust`,
    ['shop'] = 'luxury',
},
['stratumc'] = {
    ['name'] = 'Stratum',
    ['brand'] = 'Zircoflow',
    ['model'] = 'stratumc',
    ['price'] = 21000,
    ['category'] = 'coupes',
    ['hash'] = `stratumc`,
    ['shop'] = 'pdm',
},
['streiter2'] = {
    ['name'] = 'Streiter',
    ['brand'] = 'Benefactor',
    ['model'] = 'streiter2',
    ['price'] = 41000,
    ['category'] = 'coupes',
    ['hash'] = `streiter2`,
    ['shop'] = 'pdm',
},
['spritzer'] = {
    ['name'] = 'Spritzer STR',
    ['brand'] = 'Benefactor',
    ['model'] = 'spritzer',
    ['price'] = 23000,
    ['category'] = 'coupes',
    ['hash'] = `spritzer`,
    ['shop'] = 'pdm',
},
['spritzerdtm'] = {
    ['name'] = 'Spritzer DTM',
    ['brand'] = 'Benefactor',
    ['model'] = 'spritzerdtm',
    ['price'] = 71500,
    ['category'] = 'tuner',
    ['hash'] = `spritzerdtm`,
    ['shop'] = 'pdm',
},
['squaddier'] = {
    ['name'] = 'Baller Raid',
    ['brand'] = 'Gallivanter',
    ['model'] = 'squaddier',
    ['price'] = 80000,
    ['category'] = 'offroad',
    ['hash'] = `squaddier`,
    ['shop'] = 'pdm',
},
['sunrise1'] = {
    ['name'] = 'Sunrise R',
    ['brand'] = 'Maibatsu',
    ['model'] = 'sunrise1',
    ['price'] = 61000,
    ['category'] = 'tuner',
    ['hash'] = `sunrise1`,
    ['shop'] = 'luxury',
},
['vigout'] = {
    ['name'] = 'Vigero Outlaw',
    ['brand'] = 'Declasse',
    ['model'] = 'vigout',
    ['price'] = 140000,
    ['category'] = 'offroad',
    ['hash'] = `vigout`,
    ['shop'] = 'pdm',
},
['vulture'] = {
    ['name'] = 'Vulture',
    ['brand'] = 'Bravado',
    ['model'] = 'vulture',
    ['price'] = 67100,
    ['category'] = 'muscle',
    ['hash'] = `vulture`,
    ['shop'] = 'pdm',
},
['zion4'] = {
    ['name'] = 'Zion Classic Custom',
    ['brand'] = 'Übermacht',
    ['model'] = 'zion4',
    ['price'] = 48500,
    ['category'] = 'tuner',
    ['hash'] = `zion4`,
    ['shop'] = 'luxury',
},
['zr380c'] = {
    ['name'] = 'ZR-380',
    ['brand'] = 'Annis',
    ['model'] = 'zr380c',
    ['price'] = 58100,
    ['category'] = 'coupe',
    ['hash'] = `zr380c`,
    ['shop'] = 'pdm',
},
['zr380s'] = {
    ['name'] = 'ZR-380 Custom',
    ['brand'] = 'Annis',
    ['model'] = 'zr380s',
    ['price'] = 89150,
    ['category'] = 'tuner',
    ['hash'] = `zr380s`,
    ['shop'] = 'luxury',
},
